CIRCUITPY_WIFI_SSID = "Sardines"
CIRCUITPY_WIFI_PASSWORD = "LICbaby123"
CIRCUITPY_FERRY_ROUTE_ID = "r-dr5rs-er"
CIRCUITPY_FERRY_ROUTE_NAME = "ER (East River)"
CIRCUITPY_FERRY_STOP_ID = "s-dr5rubz42m-hunterspointsouth"
CIRCUITPY_FERRY_STOP_NAME = "Hunters Point South"
CIRCUITPY_FERRY_HEADSIGN = "Wall St./Pier 11"
CIRCUITPY_FERRY_COLOR = "teal"
